export default {
    SET_API_DATA: 'SET_API_DATA',
    ADD_INGREDIENT_TO_SHOPPING_LIST: 'ADD_INGREDIENT_TO_SHOPPING_LIST',
    REMOVE_INGREDIENT_FROM_SHOPPING_LIST : 'REMOVE_INGREDIENT_FROM_SHOPPING_LIST',
    RESET: 'RESET'
  };
  