name: Expo Publish
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'assets/**'
      - '*.js'
      - '*.json'
jobs:
  publish:
    name: Install, publish and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - name: Install dependencies
        run: npm install
      - run: expo publish
      - name: Build apk
        run: expo build:android -t apk --no-wait
